version: "3.6"
services:
  # API
  api:
    build: ./
    volumes:
      - ./:/usr/src/api
    command: npm run dev
    working_dir: /usr/src/api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URI: redis://redis:6379
      JWT_SECRET: SuperSecret!

  # Mongo
  mongo:
    image: mongo
    ports:
      - "27017:27107"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
